# **IRIS Flower Prediction using KNN Classification**

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

> **1. Data Pre-processing :**

In [11]:
df = pd.read_csv('/kaggle/input/iris-flower-dataset/IRIS.csv')

In [12]:
df

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [14]:
df.species.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [15]:
df.species.value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: species, dtype: int64

In [16]:
df['species'] = df['species'].replace({'Iris-setosa':1, 'Iris-versicolor':2, 'Iris-virginica':3})

In [17]:
df.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        1
1           4.9          3.0           1.4          0.2        1
2           4.7          3.2           1.3          0.2        1
3           4.6          3.1           1.5          0.2        1
4           5.0          3.6           1.4          0.2        1

In [18]:
df.tail()

sepal_length  sepal_width  petal_length  petal_width  species
145           6.7          3.0           5.2          2.3        3
146           6.3          2.5           5.0          1.9        3
147           6.5          3.0           5.2          2.0        3
148           6.2          3.4           5.4          2.3        3
149           5.9          3.0           5.1          1.8        3

In [19]:
X = df.drop('species', axis=1)
Y = df['species']

In [22]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(X, Y, test_size=0.20, random_state=42)

> **2. Create and Train KNN Classification Model :**

In [24]:
from sklearn.neighbors import KNeighborsClassifier

In [25]:
knn_clf = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
knn_clf.fit(x_train, y_train)

KNeighborsClassifier()

> **3. Predict Test Set Results :**

In [26]:
y_pred = knn_clf.predict(x_test)

In [27]:
pd.DataFrame({'Actual':y_test, 'Predicted':y_pred})

Actual  Predicted
73        2          2
18        1          1
118       3          3
78        2          2
76        2          2
31        1          1
64        2          2
141       3          3
68        2          2
82        2          2
110       3          3
12        1          1
36        1          1
9         1          1
19        1          1
56        2          2
104       3          3
69        2          2
55        2          2
132       3          3
29        1          1
127       3          3
26        1          1
128       3          3
131       3          3
145       3          3
108       3          3
143       3          3
45        1          1
30        1          1

> **4. Model Evaluation Performance :**

In [28]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [31]:
score = accuracy_score(y_test, y_pred)
print(score)

1.0


In [32]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00         9
           3       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [33]:
mat = confusion_matrix(y_test, y_pred)
print(mat)

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
